<?php
/**
 * PaymentInitiationPaymentStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PaymentInitiationPaymentStatus Class Doc Comment
 *
 * @category Class
 * @description The status of the payment.  &#x60;PAYMENT_STATUS_INPUT_NEEDED&#x60;: This is the initial state of all payments. It indicates that the payment is waiting on user input to continue processing. A payment may re-enter this state later on if further input is needed.  &#x60;PAYMENT_STATUS_INITIATED&#x60;: The payment has been successfully authorised and accepted by the financial institution but has not been executed.  &#x60;PAYMENT_STATUS_INSUFFICIENT_FUNDS&#x60;: The payment has failed due to insufficient funds.  &#x60;PAYMENT_STATUS_FAILED&#x60;: The payment has failed to be initiated. This error is retryable once the root cause is resolved.  &#x60;PAYMENT_STATUS_BLOCKED&#x60;: The payment has been blocked. This is a retryable error.  &#x60;PAYMENT_STATUS_AUTHORISING&#x60;: The payment is currently being processed. The payment will automatically exit this state when the financial institution has authorised the transaction.  &#x60;PAYMENT_STATUS_CANCELLED&#x60;: The payment was cancelled during authorisation.  &#x60;PAYMENT_STATUS_EXECUTED&#x60;: The payment has been successfully initiated and is considered complete.  &#x60;PAYMENT_STATUS_ESTABLISHED&#x60;: Indicates that the standing order has been successfully established. This state is only used for standing orders.  &#x60;PAYMENT_STATUS_REJECTED&#x60;: The payment was rejected by the financial institution.  Deprecated: These statuses will be removed in a future release.  &#x60;PAYMENT_STATUS_UNKNOWN&#x60;: The payment status is unknown.  &#x60;PAYMENT_STATUS_PROCESSING&#x60;: The payment is currently being processed. The payment will automatically exit this state when processing is complete.  &#x60;PAYMENT_STATUS_COMPLETED&#x60;: Indicates that the standing order has been successfully established. This state is only used for standing orders.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentInitiationPaymentStatus
{
    /**
     * Possible values of this enum
     */
    public const INPUT_NEEDED = 'PAYMENT_STATUS_INPUT_NEEDED';

    public const PROCESSING = 'PAYMENT_STATUS_PROCESSING';

    public const INITIATED = 'PAYMENT_STATUS_INITIATED';

    public const COMPLETED = 'PAYMENT_STATUS_COMPLETED';

    public const INSUFFICIENT_FUNDS = 'PAYMENT_STATUS_INSUFFICIENT_FUNDS';

    public const FAILED = 'PAYMENT_STATUS_FAILED';

    public const BLOCKED = 'PAYMENT_STATUS_BLOCKED';

    public const UNKNOWN = 'PAYMENT_STATUS_UNKNOWN';

    public const EXECUTED = 'PAYMENT_STATUS_EXECUTED';

    public const AUTHORISING = 'PAYMENT_STATUS_AUTHORISING';

    public const CANCELLED = 'PAYMENT_STATUS_CANCELLED';

    public const ESTABLISHED = 'PAYMENT_STATUS_ESTABLISHED';

    public const REJECTED = 'PAYMENT_STATUS_REJECTED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INPUT_NEEDED,
            self::PROCESSING,
            self::INITIATED,
            self::COMPLETED,
            self::INSUFFICIENT_FUNDS,
            self::FAILED,
            self::BLOCKED,
            self::UNKNOWN,
            self::EXECUTED,
            self::AUTHORISING,
            self::CANCELLED,
            self::ESTABLISHED,
            self::REJECTED
        ];
    }
}


