<?php
/**
 * PaystubVerificationStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PaystubVerificationStatus Class Doc Comment
 *
 * @category Class
 * @description Derived verification status.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaystubVerificationStatus
{
    /**
     * Possible values of this enum
     */
    public const PAYSTUB_VERIFICATION_STATUS_UNKNOWN = 'PAYSTUB_VERIFICATION_STATUS_UNKNOWN';

    public const PAYSTUB_VERIFICATION_STATUS_VERIFIED = 'PAYSTUB_VERIFICATION_STATUS_VERIFIED';

    public const PAYSTUB_VERIFICATION_STATUS_FRAUDULENT = 'PAYSTUB_VERIFICATION_STATUS_FRAUDULENT';

    public const NULL = 'null';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYSTUB_VERIFICATION_STATUS_UNKNOWN,
            self::PAYSTUB_VERIFICATION_STATUS_VERIFIED,
            self::PAYSTUB_VERIFICATION_STATUS_FRAUDULENT,
            self::NULL
        ];
    }
}


