<?php
/**
 * TransferEventType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TransferEventType Class Doc Comment
 *
 * @category Class
 * @description The type of event that this transfer represents.  &#x60;pending&#x60;: A new transfer was created; it is in the pending state.  &#x60;cancelled&#x60;: The transfer was cancelled by the client.  &#x60;failed&#x60;: The transfer failed, no funds were moved.  &#x60;posted&#x60;: The transfer has been successfully submitted to the payment network.  &#x60;reversed&#x60;: A posted transfer was reversed.  &#x60;swept&#x60;: The transfer was swept to / from the sweep account.  &#x60;reverse_swept&#x60;: Due to the transfer reversing, funds were pulled from or pushed back to the sweep account.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransferEventType
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const CANCELLED = 'cancelled';

    public const FAILED = 'failed';

    public const POSTED = 'posted';

    public const REVERSED = 'reversed';

    public const SWEPT = 'swept';

    public const REVERSE_SWEPT = 'reverse_swept';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::CANCELLED,
            self::FAILED,
            self::POSTED,
            self::REVERSED,
            self::SWEPT,
            self::REVERSE_SWEPT
        ];
    }
}


